# This is a basic workflow to help you get started with Actions
# see https://github.com/satu0king/Github-Documentation-With-Doxygen

name: Doxygen Action

on:
  push:
    branches: [ documentation ]


jobs:

  documentation:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html

  build-cmake:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - run: sudo apt-cache search catch

      - name: Install soundio
        run: sudo apt-get install libsoundio-dev

      - name: Install FFTW
        run: sudo apt-get install libfftw3-dev

      - name: Install GLFW
        run: sudo apt-get install libglfw3-dev

      - name: Install Catch2
        run: sudo apt-get install catch

      - name: Create a build directory
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure cmake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release
